"""Fixtures. Everything is generated by ffmpeg at test time.

No binary fixtures live in the repository. ffmpeg is invoked through
``framepicker.proc``, the one module allowed to start processes, so the
"no direct subprocess" rule holds for the test suite too.
"""

from __future__ import annotations

import os

import pytest

from framepicker import proc

FFMPEG = "ffmpeg"

CLIP_WIDTH = 320
CLIP_HEIGHT = 240
CLIP_FPS = 10
#: Pixels the burnt-in marker moves per frame in the counter fixture.
MARKER_STEP = 4
MARKER_HEIGHT = 20
MARKER_BAND_TOP = CLIP_HEIGHT + 4


def _have_ffmpeg() -> bool:
    return proc.executable(FFMPEG) is not None


requires_ffmpeg = pytest.mark.skipif(not _have_ffmpeg(), reason="ffmpeg not on PATH")


def _run_ffmpeg(argv: list[str]) -> None:
    result = proc.run([FFMPEG, "-hide_banner", "-loglevel", "error", "-y", *argv], timeout=300)
    if not result.ok:
        raise RuntimeError(f"ffmpeg fixture build failed: {result.stderr_text()}")


def _make_clip(path: str, seconds: float, extra_filters: str = "", fps: int = CLIP_FPS) -> str:
    argv = [
        "-f", "lavfi",
        "-i", f"testsrc2=s={CLIP_WIDTH}x{CLIP_HEIGHT}:r={fps}:d={seconds}",
    ]
    if extra_filters:
        argv += ["-vf", extra_filters]
    argv += ["-pix_fmt", "yuv420p", "-c:v", "libx264", "-crf", "16", "-g", "10", path]
    _run_ffmpeg(argv)
    return path


@pytest.fixture(scope="session")
def media_dir(tmp_path_factory) -> str:
    return str(tmp_path_factory.mktemp("media"))


@pytest.fixture(scope="session")
def normal_clip(media_dir) -> str:
    if not _have_ffmpeg():
        pytest.skip("ffmpeg not on PATH")
    return _make_clip(os.path.join(media_dir, "normal.mp4"), 8)


@pytest.fixture(scope="session")
def short_clip(media_dir) -> str:
    """Five seconds - too short to yield six frames two seconds apart."""
    if not _have_ffmpeg():
        pytest.skip("ffmpeg not on PATH")
    return _make_clip(os.path.join(media_dir, "short.mp4"), 5)


@pytest.fixture(scope="session")
def blurred_clip(media_dir) -> str:
    if not _have_ffmpeg():
        pytest.skip("ffmpeg not on PATH")
    return _make_clip(os.path.join(media_dir, "blurred.mp4"), 6, "gblur=sigma=6")


@pytest.fixture(scope="session")
def flat_clip(media_dir) -> str:
    """Low contrast, low saturation copy - stands in for ungraded log footage.

    The name carries a D-Log hint on purpose: the filename branch of the log
    detector is part of what this fixture exercises.
    """
    if not _have_ffmpeg():
        pytest.skip("ffmpeg not on PATH")
    return _make_clip(
        os.path.join(media_dir, "DJI_0001_DLOG.mp4"),
        8,
        "eq=contrast=0.22:saturation=0.12:brightness=0.06",
    )


@pytest.fixture(scope="session")
def counter_clip(media_dir) -> str:
    """testsrc2 with a burnt-in frame counter.

    A white block in a black band under the picture moves ``MARKER_STEP``
    pixels per frame, so the frame number can be read back out of an exported
    still without OCR.
    """
    if not _have_ffmpeg():
        pytest.skip("ffmpeg not on PATH")
    path = os.path.join(media_dir, "counter.mp4")
    _run_ffmpeg([
        "-f", "lavfi", "-i", f"testsrc2=s={CLIP_WIDTH}x{CLIP_HEIGHT}:r={CLIP_FPS}:d=6",
        "-f", "lavfi", "-i", f"color=c=white:s={MARKER_STEP}x{MARKER_HEIGHT}:r={CLIP_FPS}",
        "-filter_complex",
        f"[0:v]pad={CLIP_WIDTH}:{CLIP_HEIGHT + 24}:0:0:black[p];"
        f"[p][1:v]overlay=x='{MARKER_STEP}*n':y={MARKER_BAND_TOP}:shortest=1",
        "-pix_fmt", "yuv420p", "-c:v", "libx264", "-crf", "14", "-g", "10", path,
    ])
    return path


def read_marker_x(image_bgr) -> float | None:
    """Centre column of the burnt-in marker, or ``None`` if there is none."""
    import cv2
    import numpy as np

    gray = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2GRAY)
    height, width = gray.shape[:2]
    top = int(round(MARKER_BAND_TOP / (CLIP_HEIGHT + 24) * height)) + 2
    bottom = min(height, top + max(4, int(MARKER_HEIGHT / (CLIP_HEIGHT + 24) * height) - 4))
    band = gray[top:bottom, :]
    if band.size == 0:
        return None
    columns = band.mean(axis=0)
    hot = np.where(columns > 160)[0]
    if hot.size == 0:
        return None
    return float(hot.mean()) / width * CLIP_WIDTH


@pytest.fixture(scope="session")
def counter_markers(counter_clip) -> list[float]:
    """Marker position of every frame of the counter clip, read sequentially."""
    import cv2

    capture = cv2.VideoCapture(counter_clip)
    markers: list[float] = []
    while True:
        ok, frame = capture.read()
        if not ok:
            break
        markers.append(read_marker_x(frame) or -1.0)
    capture.release()
    assert markers, "counter fixture produced no frames"
    return markers


@pytest.fixture(scope="session")
def unreadable_file(media_dir) -> str:
    path = os.path.join(media_dir, "broken.mp4")
    with open(path, "wb") as handle:
        handle.write(b"this is not a video file, not even close\n" * 20)
    return path
